name 'roshi_deployment'
maintainer 'Rajaie'
maintainer_email 'rajaie.alkorani@gmail.com'
license 'all_rights'
description 'Installs/Configures roshi_deployment'
long_description 'Installs/Configures roshi_deployment'
version '0.1.0'

depends 'apt'
depends 'nginx'
